AllCops:
  TargetRubyVersion: 2.5

Documentation:
  Enabled: false

# Style
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/SignalException:
  EnforcedStyle: only_raise

Style/BlockDelimiters:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Metrics
Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# Layout
Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
