AllCops:
  TargetRubyVersion: 2.0+

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ExtraSpacing:
  AllowForAlignment: true

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/BlockDelimiters:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
